version: "3.9"
services:

  db:
    image: postgres:15.3-alpine
    volumes:
      - weather_db:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    env_file:
      - ./.env

  redis:
    image: redis:7.0-alpine

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: python manage.py runserver 0:8000

volumes:
  weather_db:
