# Generated by Django 4.2 on 2023-06-02 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdata",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="collector.city"
            ),
        ),
    ]
