# Generated by Django 4.2 on 2023-06-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0002_alter_weatherdata_city"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["-population"],
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.AlterField(
            model_name="city",
            name="population",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
