# Generated by Django 4.2.1 on 2023-05-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_weather_dt_weather_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='dt',
            field=models.IntegerField(null=True),
        ),
    ]
